### ISSUE TITLE
Add support for pickled data

### ISSUE THREAD

**Issue by frague59** [MattMin/a-redis#11]
Hi, 

I'm using this amazing plugin with PyCharm (python). I use pickle as serialization protocol for my sessions - it would be interesting to add support for pickle format in the "View as" select !

Thanks !

**Comment by MattMin** [comment]
This is the problem of serialization and deserialization, should have nothing to do with formatting; if I use java to deserialize the data into java objects, then how do I display it, using json?

**Comment by frague59** [comment]
Yep, could be a good option...
