### ISSUE TITLE
设置key时，ttl会被覆盖修改成-1

### ISSUE THREAD

**Issue by gerryhjs** [MattMin/a-redis#14]
使用jedis设置key时，如果有ttl可以使用之前的ttl值，防止过期时间被覆盖掉

**Comment by MattMin** [comment]
Redis就是这样设计的, 可以参考: [Redis doc](https://redis.io/commands/expire)

**Comment by gerryhjs** [comment]
@MattMin 我尝试性改了一下可以保留ttl 就不提pr了您看下要是觉得有用可以改一下
`            case String:
                try (Jedis jedis = redisPoolManager.getJedis(dbInfo.getIndex())) {
                    try {
                        **jedis.set(key, newValue, new SetParams().ex(Long.parseLong(ttlValue)));**
                    } catch (Exception e) {
                        jedis.set(key, newValue);
                    }
                }
                break;`

**Comment by jumkey** [comment]
你这时间已经不是原来的时间了，与其加个不准的时间 还不如让用户自己设置时间。参考其他客户端也是-1

**Comment by gerryhjs** [comment]
好的 那我先close了
