### ISSUE TITLE
Connection setting font color "succeeded" is not so clear.

### ISSUE THREAD

**Issue by gerryhjs** [MattMin/a-redis#18]
![image](https://user-images.githubusercontent.com/45413498/143966125-368522bf-5670-4ab7-9f71-4c9855c0bc8f.png)
Peformance not so clear in idea Darcula theme. I though it is beacause use color "green" for "succeeded".

**Comment by MattMin** [comment]
![image](https://user-images.githubusercontent.com/23516441/144008115-d9839ef1-d056-4ad5-a05c-f6ee0fc72514.png)
你用的主题名字叫什么

**Comment by gerryhjs** [comment]
我用的就是官方的Darcula 是ubuntu下的 按钮样式是用了Material UI的outline 按钮样式

**Comment by gerryhjs** [comment]
应该是第三方插件引起的问题 我把Material UI的插件禁用之后正常了
![image](https://user-images.githubusercontent.com/45413498/144009046-2cc4ea2a-4303-4b17-b22b-68c417fc88ea.png)
