### ISSUE TITLE
UI Blocked while loading data

### ISSUE THREAD

**Issue by lllvantis** [MattMin/a-redis#23]
开启链接的时候 因为读DB下的key数量导致整个软件卡住 希望可以解决

**Comment by jumkey** [comment]
https://github.com/MattMin/a-redis/blob/6d4b992c1f97ceda833e9a8f311f5e036d2f22bb/src/main/java/com/mzyupc/aredis/view/KeyTreeDisplayPanel.java#L93-L98
这段应该可以改成
```java
allKeys = Collections.emptyList();
```
不然打开大db还是会阻塞 @MattMin

**Comment by MattMin** [comment]
在 beta-0.8.0 中已修复
