### ISSUE TITLE
Redis Connection PopUp Use to English

### ISSUE THREAD

**Issue by newbalancer** [MattMin/a-redis#29]
Hi,

I'm using this plugin with intellij (version.2022.1.4) 

how to use english?

Thanks ! 👍

<img width="815" alt="스크린샷 2022-07-30 오전 11 58 23" src="https://user-images.githubusercontent.com/53357210/181868199-b38cafb4-8f40-4ce6-94e0-e5913b565e56.png">

**Comment by MattMin** [comment]
You may have raised the issue in the wrong repository. My plugin is called 'Redis Helper' in jetbrains marketplace.
![image](https://user-images.githubusercontent.com/23516441/182059395-73a6b214-189e-4ff3-8665-ac90a07449da.png)

**Comment by gerryhjs** [comment]
BTW, I have ask Jetbrains to mark Gerry Redis as deprecated now to avoid user find wrong plugin with Redis Helper. https://plugins.jetbrains.com/plugin/19319-gerry-redis
