### ISSUE TITLE
Issues with large datasets in redis

### ISSUE THREAD

**Issue by mvodanovic** [MattMin/a-redis#37]
We have a redis instance with a large data set (almost 7 million entries in one DB) and if I try to use this plugin, it's **really** slow. I guess that at some point it's iterating through everything in redis. It should never iterate through everything, just through one page. Maybe it's also doing one page? But the page size is set to 10000 items, it might be that even that is too slow.

**Comment by MattMin** [comment]
I'll think about how to optimise this

**Comment by MattMin** [comment]
[1.0.0](https://github.com/MattMin/a-redis/releases/tag/1.0.0) has resolved this issue, and JetBrains Marketplace has been synchronized accordingly.
