### ISSUE TITLE
展开库的节点和key的节点很卡,建议优化

### ISSUE THREAD

**Issue by jiangguilong2000** [MattMin/a-redis#44]
耗时大概在15秒
![image](https://github.com/MattMin/a-redis/assets/5009933/385aeaeb-ab8f-490d-b47b-dd7e67aa6b17)

**Comment by MattMin** [comment]
我测了一下，使用的是腾讯云里搭建的 Redis:7.2.0, 500 个 DB, 每个 DB 中有 10000+ 的数据，无论是获取 DB 还是获取 DB 中的 Key，都在 1s 内能完成，如果你的问题还是存在，请检查以下是不是网络的问题，或者给出更详细的上下文
